export const routesConfig = {
  "loginUrl":"rest-auth/login/",
  "signupUrl" : "rest-auth/registration/",
  "logoutUrl" : "rest-auth/logout/",
  "passwordResetUrl" : "rest-auth/password/reset/",
  "passwordChangeUrl" : "rest-auth/password/change/",
  "contactsUrl" : "api/contacts/",
  "contactDetailUrl" : "api/contacts/{ID}/",
  "contactRequestsUrl" : "api/contact-requests/",
  "contactRequestDetailUrl" : "api/contact-requests/{ID}/",
  "addReferralUrl" : "api/contacts/create-contact-from-referral",
  "getOutlookContactsUrl" : "https://graph.microsoft.com/v1.0/me/contacts",
  "importOutlookContactsUrl" : "api/contacts/import_outlook_contacts/",
  "groupsUrl"  : "api/contact-groups/",
  "grouptDetailUrl"  : "api/contact-groups/{ID}/",
  "userProfilesUrl"  : "api/users/",
  "shareableProfilesUrl"  : "api/shareable-profiles/",
  "shareableProfileDetailUrl"  : "api/shareable-profiles/{ID}/",
  "shareableProfileDecodeUrl"  : "api/shareable-profiles/decode_profile_url/",
  "settingsUrl" : "rest-auth/user/",
  "settingsRefreshUrl": "rest-auth/user/refresh/",
  "contactPermissionsUrl": "api/contact-permissions/",
  "contactPermissionsDetailUrl": "api/contact-permissions/{ID}/",
  "linkedinConnectUrl": "rest-auth/connect_linkedin/",
  "linkedinLoginUrl": "rest-auth/linkedin/",
  "outlookTokenUrl": "api/get-outlook-token/"
};
